extends Node

const WEAPONS: Dictionary = {
	"minigun": {
		"name": "Minigun",
		"description": "Rapid-fire bullets. Great for sustained damage.",
		"damage": 8,
		"fire_rate": 0.08,
		"range": 320,
		"projectile_speed": 500,
		"gem_cost": 0,
		"arena_unlock": 0,
		"color": Color(0.7, 0.7, 0.75),
		"type": "bullet",
	},
	"shotgun": {
		"name": "Shotgun",
		"description": "Fires a spread of pellets at close range.",
		"damage": 6,
		"fire_rate": 0.7,
		"range": 180,
		"projectile_speed": 400,
		"gem_cost": 150,
		"arena_unlock": 0,
		"color": Color(0.55, 0.45, 0.35),
		"type": "spread",
		"pellets": 6,
	},
	"rocket": {
		"name": "Rocket Launcher",
		"description": "Explosive rockets with area damage.",
		"damage": 35,
		"fire_rate": 1.2,
		"range": 400,
		"projectile_speed": 280,
		"gem_cost": 300,
		"arena_unlock": 1,
		"color": Color(0.9, 0.4, 0.1),
		"type": "explosive",
		"blast_radius": 60,
	},
	"laser": {
		"name": "Laser Cannon",
		"description": "Piercing beam that ignores armor.",
		"damage": 22,
		"fire_rate": 0.5,
		"range": 450,
		"projectile_speed": 800,
		"gem_cost": 400,
		"arena_unlock": 1,
		"color": Color(1.0, 0.2, 0.3),
		"type": "piercing",
	},
	"saw": {
		"name": "Buzz Saw",
		"description": "Spinning melee blade for close combat.",
		"damage": 18,
		"fire_rate": 0.3,
		"range": 70,
		"projectile_speed": 0,
		"gem_cost": 250,
		"arena_unlock": 0,
		"color": Color(0.6, 0.6, 0.65),
		"type": "melee",
	},
	"tesla": {
		"name": "Tesla Coil",
		"description": "Chain lightning jumps between nearby enemies.",
		"damage": 15,
		"fire_rate": 0.6,
		"range": 250,
		"projectile_speed": 600,
		"gem_cost": 500,
		"arena_unlock": 2,
		"color": Color(0.3, 0.7, 1.0),
		"type": "chain",
		"chain_count": 3,
	},
	"flame": {
		"name": "Flamethrower",
		"description": "Short-range cone that burns over time.",
		"damage": 5,
		"fire_rate": 0.1,
		"range": 140,
		"projectile_speed": 300,
		"gem_cost": 350,
		"arena_unlock": 2,
		"color": Color(1.0, 0.5, 0.0),
		"type": "flame",
		"dot_damage": 3,
		"dot_duration": 2.0,
	},
	"plasma": {
		"name": "Plasma Rifle",
		"description": "High-damage energy bolts.",
		"damage": 40,
		"fire_rate": 0.9,
		"range": 380,
		"projectile_speed": 450,
		"gem_cost": 600,
		"arena_unlock": 3,
		"color": Color(0.5, 0.0, 1.0),
		"type": "bullet",
	},
	"missile": {
		"name": "Missile Pod",
		"description": "Homing missiles track their target.",
		"damage": 28,
		"fire_rate": 1.5,
		"range": 500,
		"projectile_speed": 200,
		"gem_cost": 700,
		"arena_unlock": 3,
		"color": Color(0.8, 0.8, 0.2),
		"type": "homing",
	},
	"drill": {
		"name": "Power Drill",
		"description": "Melee drill that shreds armor.",
		"damage": 25,
		"fire_rate": 0.4,
		"range": 65,
		"projectile_speed": 0,
		"gem_cost": 450,
		"arena_unlock": 2,
		"color": Color(0.75, 0.55, 0.2),
		"type": "melee",
		"armor_break": true,
	},
	"freeze": {
		"name": "Freeze Ray",
		"description": "Slows enemies on hit.",
		"damage": 12,
		"fire_rate": 0.45,
		"range": 300,
		"projectile_speed": 350,
		"gem_cost": 550,
		"arena_unlock": 3,
		"color": Color(0.6, 0.9, 1.0),
		"type": "slow",
		"slow_factor": 0.4,
		"slow_duration": 2.5,
	},
	"poison": {
		"name": "Poison Sprayer",
		"description": "Applies stacking poison damage.",
		"damage": 4,
		"fire_rate": 0.15,
		"range": 200,
		"projectile_speed": 250,
		"gem_cost": 400,
		"arena_unlock": 4,
		"color": Color(0.3, 0.9, 0.2),
		"type": "poison",
		"dot_damage": 5,
		"dot_duration": 4.0,
	},
	"railgun": {
		"name": "Railgun",
		"description": "Devastating long-range shot with charge time.",
		"damage": 80,
		"fire_rate": 2.0,
		"range": 600,
		"projectile_speed": 1200,
		"gem_cost": 900,
		"arena_unlock": 4,
		"color": Color(0.2, 0.8, 0.9),
		"type": "piercing",
	},
	"boomerang": {
		"name": "Saw Launcher",
		"description": "Throws a returning saw blade.",
		"damage": 20,
		"fire_rate": 0.8,
		"range": 280,
		"projectile_speed": 350,
		"gem_cost": 500,
		"arena_unlock": 3,
		"color": Color(0.85, 0.85, 0.9),
		"type": "boomerang",
	},
	"shield_gen": {
		"name": "Shield Generator",
		"description": "Projects a temporary energy shield.",
		"damage": 0,
		"fire_rate": 5.0,
		"range": 0,
		"projectile_speed": 0,
		"gem_cost": 650,
		"arena_unlock": 4,
		"color": Color(0.2, 0.5, 1.0),
		"type": "shield",
		"shield_amount": 80,
		"shield_duration": 4.0,
	},
	"mortar": {
		"name": "Mortar",
		"description": "Lobs arcing explosives over obstacles.",
		"damage": 45,
		"fire_rate": 1.8,
		"range": 420,
		"projectile_speed": 200,
		"gem_cost": 750,
		"arena_unlock": 5,
		"color": Color(0.4, 0.35, 0.3),
		"type": "mortar",
		"blast_radius": 80,
	},
	"emp": {
		"name": "EMP Blaster",
		"description": "Disables enemy weapons briefly.",
		"damage": 10,
		"fire_rate": 2.5,
		"range": 280,
		"projectile_speed": 400,
		"gem_cost": 800,
		"arena_unlock": 5,
		"color": Color(0.9, 0.9, 0.3),
		"type": "emp",
		"disable_duration": 2.0,
	},
	"gravity": {
		"name": "Gravity Well",
		"description": "Pulls enemies inward and damages them.",
		"damage": 8,
		"fire_rate": 3.0,
		"range": 200,
		"projectile_speed": 0,
		"gem_cost": 950,
		"arena_unlock": 6,
		"color": Color(0.4, 0.1, 0.6),
		"type": "gravity",
		"pull_radius": 120,
	},
	"photon": {
		"name": "Photon Cannon",
		"description": "Ultra-fast photon bursts.",
		"damage": 30,
		"fire_rate": 0.25,
		"range": 400,
		"projectile_speed": 900,
		"gem_cost": 850,
		"arena_unlock": 6,
		"color": Color(1.0, 1.0, 0.8),
		"type": "bullet",
	},
	"vortex": {
		"name": "Vortex Launcher",
		"description": "Creates a damaging vortex at impact point.",
		"damage": 12,
		"fire_rate": 2.2,
		"range": 350,
		"projectile_speed": 300,
		"gem_cost": 1000,
		"arena_unlock": 7,
		"color": Color(0.6, 0.0, 0.8),
		"type": "vortex",
		"vortex_duration": 3.0,
		"vortex_radius": 90,
	},
}

const CHASSIS: Dictionary = {
	"light": {
		"name": "Light Frame",
		"hp": 100,
		"speed": 220,
		"armor": 0,
		"gem_cost": 0,
		"arena_unlock": 0,
		"color": Color(0.4, 0.7, 0.9),
	},
	"medium": {
		"name": "Medium Frame",
		"hp": 150,
		"speed": 180,
		"armor": 10,
		"gem_cost": 200,
		"arena_unlock": 1,
		"color": Color(0.5, 0.55, 0.6),
	},
	"heavy": {
		"name": "Heavy Frame",
		"hp": 220,
		"speed": 140,
		"armor": 25,
		"gem_cost": 450,
		"arena_unlock": 2,
		"color": Color(0.45, 0.4, 0.42),
	},
	"titan": {
		"name": "Titan Frame",
		"hp": 300,
		"speed": 110,
		"armor": 40,
		"gem_cost": 800,
		"arena_unlock": 4,
		"color": Color(0.6, 0.3, 0.25),
	},
	"stealth": {
		"name": "Stealth Frame",
		"hp": 90,
		"speed": 260,
		"armor": 5,
		"gem_cost": 600,
		"arena_unlock": 3,
		"color": Color(0.2, 0.25, 0.3),
	},
}

const ARENAS: Array[Dictionary] = [
	{
		"id": 0,
		"name": "Scrap Yard",
		"description": "Rusty junk and broken bots litter the arena.",
		"trophy_required": 0,
		"gem_reward_win": 15,
		"gem_reward_boss": 100,
		"bg_color": Color(0.35, 0.28, 0.22),
		"accent": Color(0.7, 0.5, 0.3),
		"weapon_pool": ["minigun", "shotgun", "saw"],
		"chassis_pool": ["light"],
		"boss": {
			"name": "Junk Titan",
			"hp": 500,
			"damage_mult": 1.2,
			"speed": 90,
			"weapons": ["shotgun", "saw"],
			"color": Color(0.55, 0.4, 0.3),
			"size": 1.8,
		},
	},
	{
		"id": 1,
		"name": "Factory Floor",
		"description": "Conveyor belts and industrial hazards.",
		"trophy_required": 50,
		"gem_reward_win": 20,
		"gem_reward_boss": 150,
		"bg_color": Color(0.25, 0.27, 0.3),
		"accent": Color(0.8, 0.6, 0.2),
		"weapon_pool": ["minigun", "shotgun", "rocket", "laser", "saw"],
		"chassis_pool": ["light", "medium", "heavy"],
		"boss": {
			"name": "Tombstone",
			"hp": 650,
			"damage_mult": 1.3,
			"speed": 70,
			"weapons": ["laser", "minigun", "rocket"],
			"color": Color(0.3, 0.35, 0.4),
			"size": 2.0,
			"model": "res://assets/Boss1.1/tombstone_2018_-_battlebots.glb",
			"model_scale": 1.0,
		},
	},
	{
		"id": 2,
		"name": "Volcano Forge",
		"description": "Molten lava flows beneath metal grating.",
		"trophy_required": 120,
		"gem_reward_win": 28,
		"gem_reward_boss": 200,
		"bg_color": Color(0.4, 0.15, 0.1),
		"accent": Color(1.0, 0.4, 0.1),
		"weapon_pool": ["flame", "rocket", "tesla", "drill", "minigun"],
		"chassis_pool": ["medium", "heavy"],
		"boss": {
			"name": "Magma Golem",
			"hp": 800,
			"damage_mult": 1.4,
			"speed": 60,
			"weapons": ["flame", "mortar", "drill"],
			"color": Color(0.9, 0.3, 0.1),
			"size": 2.2,
		},
	},
	{
		"id": 3,
		"name": "Ice Citadel",
		"description": "Frozen fortress with slippery floors.",
		"trophy_required": 200,
		"gem_reward_win": 35,
		"gem_reward_boss": 280,
		"bg_color": Color(0.6, 0.75, 0.85),
		"accent": Color(0.3, 0.6, 0.9),
		"weapon_pool": ["freeze", "laser", "plasma", "missile", "boomerang"],
		"chassis_pool": ["light", "medium", "stealth"],
		"boss": {
			"name": "Frost Queen",
			"hp": 750,
			"damage_mult": 1.35,
			"speed": 100,
			"weapons": ["freeze", "laser", "missile"],
			"color": Color(0.7, 0.85, 1.0),
			"size": 1.7,
		},
	},
	{
		"id": 4,
		"name": "Toxic Swamp",
		"description": "Acid pools and poisonous fumes.",
		"trophy_required": 300,
		"gem_reward_win": 42,
		"gem_reward_boss": 350,
		"bg_color": Color(0.2, 0.35, 0.15),
		"accent": Color(0.4, 0.9, 0.2),
		"weapon_pool": ["poison", "railgun", "shield_gen", "shotgun", "tesla"],
		"chassis_pool": ["medium", "heavy", "titan"],
		"boss": {
			"name": "Plague Hound",
			"hp": 900,
			"damage_mult": 1.5,
			"speed": 130,
			"weapons": ["poison", "railgun", "saw"],
			"color": Color(0.3, 0.6, 0.2),
			"size": 1.9,
		},
	},
	{
		"id": 5,
		"name": "Neon City",
		"description": "Cyberpunk streets glow with neon lights.",
		"trophy_required": 420,
		"gem_reward_win": 50,
		"gem_reward_boss": 450,
		"bg_color": Color(0.1, 0.08, 0.18),
		"accent": Color(1.0, 0.0, 0.8),
		"weapon_pool": ["emp", "mortar", "plasma", "photon", "laser"],
		"chassis_pool": ["stealth", "medium", "heavy"],
		"boss": {
			"name": "Cyber Overlord",
			"hp": 1000,
			"damage_mult": 1.55,
			"speed": 110,
			"weapons": ["emp", "photon", "plasma"],
			"color": Color(0.8, 0.1, 0.9),
			"size": 2.1,
		},
	},
	{
		"id": 6,
		"name": "Space Station",
		"description": "Zero-gravity combat in orbit.",
		"trophy_required": 550,
		"gem_reward_win": 60,
		"gem_reward_boss": 550,
		"bg_color": Color(0.05, 0.05, 0.12),
		"accent": Color(0.5, 0.7, 1.0),
		"weapon_pool": ["gravity", "photon", "missile", "railgun", "shield_gen"],
		"chassis_pool": ["light", "stealth", "titan"],
		"boss": {
			"name": "Orbital Destroyer",
			"hp": 1200,
			"damage_mult": 1.6,
			"speed": 85,
			"weapons": ["gravity", "railgun", "missile"],
			"color": Color(0.3, 0.4, 0.7),
			"size": 2.4,
		},
	},
	{
		"id": 7,
		"name": "Ancient Ruins",
		"description": "Crumbling temples hold forgotten power.",
		"trophy_required": 700,
		"gem_reward_win": 75,
		"gem_reward_boss": 700,
		"bg_color": Color(0.35, 0.3, 0.22),
		"accent": Color(0.9, 0.75, 0.3),
		"weapon_pool": ["vortex", "boomerang", "plasma", "tesla", "mortar"],
		"chassis_pool": ["heavy", "titan", "medium"],
		"boss": {
			"name": "Stone Colossus",
			"hp": 1500,
			"damage_mult": 1.8,
			"speed": 50,
			"weapons": ["vortex", "mortar", "railgun"],
			"color": Color(0.6, 0.55, 0.45),
			"size": 2.6,
		},
	},
	{
		"id": 8,
		"name": "Void Nexus",
		"description": "The final arena at the edge of reality.",
		"trophy_required": 900,
		"gem_reward_win": 100,
		"gem_reward_boss": 1000,
		"bg_color": Color(0.08, 0.02, 0.12),
		"accent": Color(0.7, 0.0, 1.0),
		"weapon_pool": ["vortex", "gravity", "emp", "photon", "railgun", "plasma"],
		"chassis_pool": ["titan", "stealth", "heavy"],
		"boss": {
			"name": "Void Emperor",
			"hp": 2000,
			"damage_mult": 2.0,
			"speed": 95,
			"weapons": ["vortex", "gravity", "photon", "emp"],
			"color": Color(0.3, 0.0, 0.5),
			"size": 2.8,
		},
	},
]

const GEM_PACKS: Array[Dictionary] = [
	{"gems": 100, "cost_trophies": 0, "label": "Daily Bonus", "daily": true},
	{"gems": 250, "cost_trophies": 0, "label": "Battle Pass Reward", "battle_pass": true},
	{"gems": 500, "cost_trophies": 30, "label": "Gem Cache"},
	{"gems": 1200, "cost_trophies": 70, "label": "Gem Vault"},
	{"gems": 3000, "cost_trophies": 150, "label": "Gem Treasury"},
]

const STARTING_GEMS := 150
const STARTING_WEAPON := "minigun"
const STARTING_CHASSIS := "light"
const MAX_WEAPON_SLOTS := 3


func get_weapon(id: String) -> Dictionary:
	return WEAPONS.get(id, {})


func get_chassis(id: String) -> Dictionary:
	return CHASSIS.get(id, {})


func get_arena(arena_id: int) -> Dictionary:
	if arena_id >= 0 and arena_id < ARENAS.size() and ARENAS[arena_id].get("id", arena_id) == arena_id:
		return ARENAS[arena_id]
	for arena in ARENAS:
		if arena.get("id", -1) == arena_id:
			return arena
	return {}


func get_unlocked_arenas(trophies: int) -> Array[int]:
	var result: Array[int] = []
	for arena in ARENAS:
		if trophies >= arena.trophy_required:
			result.append(arena.id)
	return result


func random_ai_loadout(arena_id: int, difficulty: float = 1.0) -> Dictionary:
	var arena := get_arena(arena_id)
	if arena.is_empty():
		return {"chassis": "light", "weapons": ["minigun"]}
	var chassis_pool: Array = arena.get("chassis_pool", ["light"])
	var weapon_pool: Array = arena.get("weapon_pool", ["minigun"])
	var chassis_id: String = chassis_pool[randi() % chassis_pool.size()]
	var weapons: Array[String] = []
	var slot_count := mini(randi_range(1, MAX_WEAPON_SLOTS), weapon_pool.size())
	var shuffled := weapon_pool.duplicate()
	shuffled.shuffle()
	for i in slot_count:
		weapons.append(shuffled[i])
	return {"chassis": chassis_id, "weapons": weapons, "difficulty": difficulty}
